# Generated by Django 4.0.6 on 2022-08-03 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reactvideo_delete_react'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactvideo',
            old_name='post_id',
            new_name='video_id',
        ),
    ]
