# Generated by Django 4.0.6 on 2022-08-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='comment',
        ),
    ]
