# Generated by Django 4.0.6 on 2022-08-09 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_save_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Save',
            new_name='Saved',
        ),
    ]
